# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ru_excel}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sokolov Yura aka funny_falcon"]
  s.date = %q{2011-06-24}
  s.description = %q{Port of pyExcelerator tunned for faster .xls generation}
  s.email = %q{funny.falcon@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
    "Rakefile",
    "VERSION",
    "examples/big-16Mb_test.rb",
    "examples/test_multiline.rb",
    "examples/test_utf8.rb",
    "lib/ru_excel.rb",
    "lib/ru_excel/biff_records.rb",
    "lib/ru_excel/bitmap.rb",
    "lib/ru_excel/cell.rb",
    "lib/ru_excel/column.rb",
    "lib/ru_excel/compound_doc.rb",
    "lib/ru_excel/deco.rb",
    "lib/ru_excel/excel_magic.rb",
    "lib/ru_excel/formatting.rb",
    "lib/ru_excel/row.rb",
    "lib/ru_excel/style.rb",
    "lib/ru_excel/unicode_utils.rb",
    "lib/ru_excel/workbook.rb",
    "lib/ru_excel/worksheet.rb",
    "ru_excel.gemspec"
  ]
  s.homepage = %q{http://github.com/funny-falcon/ru_excel}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ru-excel}
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Fast writting of MsExcel files (port of pyExcelerator)}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

